### ISSUE TITLE
[Bug Report]: Mobs can't use Custom Enchants

### ISSUE THREAD

**Issue by Epiphania-Regina** [Crazy-Crew/CrazyEnchantments#765]
### Server Version

1.20.2

### Server Platform

Purpur

### Describe the bug

Hello, I am a Purpur using and I noticed that mobs can't use custom enchantments, I wanted to create a few custom bosses that me and my girlfriends could fight for fun on our SMP, please fix it..

### Steps to reproduce

1. Summon a mob with CanPickUpLoot set as true
2. Give it custom enchanted gear
3. The mob can't make use of the enchantments, but I and my besties can

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by Epiphania-Regina** [comment]
I hope I followed the rules or something idk how github works i am new

**Comment by RulerOfEternity** [comment]
I requested this before, this isn't really a bug report as much as it is a feature request, it was rejected because of potential lag concerns.

**Comment by ryderbelserion** [comment]
Correct, It is not a bug. It is intentional that they only work for players.

Mobs can be done at some point once a few more concerns around enchant handling are addressed, but it's not a priority as adding more places where things can go wrong is not the best idea right now.

Our plugins' focus outside of small features are mainly in performance gains and improvements of the current features and how they function. 

You can edit your post to follow the suggestion format or close this issue and create a new one.

**Comment by Epiphania-Regina** [comment]
Well I gtg, can't you just put it in your private features list or something, I am closing this request but won't open a new one, k bye
